name: neural-barrier
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy>=1.24.0
  - scipy
  - matplotlib
  - pandas
  - tqdm
  - pyyaml
  - pip
  - pip:
    - torch>=2.4.0
    - cvxpy
    - gurobipy
    - onnxruntime
    - sortedcontainers
    - scikit-learn
    - chardet
    - onnx2pytorch
    - psutil
